spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            trust: smtp.gmail.com
  sql:
    init:
      mode: always

app:
  allowed-origins: ${ALLOWED_ORIGINS}
#jwt:
#  secret: ${JWT_SECRET}
#  accessTokenExpirationMs: 900000 # 15 min in milliseconds
#  refreshTokenExpirationMs: 604800000 # 7 days in milliseconds

