name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main,dev]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      # 1 checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clearing as much disk space as possible
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQ
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          sudo docker builder prune -a

      # intialize python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # install dependencies
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r api/requirements.txt

      # run pre-commit checks again
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
